### ISSUE TITLE
Доработки/косяки/баги

### ISSUE THREAD

**Issue by ice-death** [userbq201/banners#15]
1) При создании гифки выводится вес каждого кадра. Можно ли добавить вывод общего веса гифки?	
2) Нет возможности листать кадры при создании заглушки	http://joxi.ru/5mdgww8Svl0kDr
3) Бордер виден только сверху и слева	http://joxi.ru/Drlgq83H41LMlA
4) Нет возможности выбрать вид заглушки, если нужна статичная картинка, снимаю галочку с чеr-бокса gif и блок просто схлопывается	http://joxi.ru/ZrJz33Dc1xDM8r
5) Непонятно сохранилась ли заглушка или нет - не хватает обратной связи	
6) Не работает кнопка "Восстановить исходное качество"	
7) При прошивке под яндекс баннера с уже прописанной абсолютной ссылкой на библиотеки create.js программа снова вставляет в код скрипт с абсолютной ссылкой на библиотеку	http://joxi.ru/823d00Zt6y33wA
8) Когда делаешь заглушку для длинного по ширине баннера, например, для резины с минималкой 1100 скрин кадра зарезается и вообще пропадает возможность регулировать паузу между кадрами	http://joxi.ru/5mdgww8Svl0nor
9) Необходимо выводить время в сек (номер кадра/fps) 	http://joxi.ru/Dr8Rbb8ckqvWp2
10) Баннеры с большими разсмерами не помещаются в окно. Как работать с таким баннером?	http://joxi.ru/52agoo4SGweaBr
11) Добавить возможность выбрать вид заглушки, если нужна статичная картинка, также возможность сохранить в png. 
12) Сохраненная статичная картинка в гиф потеряла цвета - девушка превратилась в труп,	http://joxi.ru/RmzE88WiWxwxlr
12) Добавить возможность изменять уровень качества, если нет галки gif	http://joxi.ru/Vm6Zpp0cxNbNMm

**Comment by userbq201** [comment]
#14 
#15
#16
#17
#18
#19
#20
#21
#22
#23
#24
#25
#26
#27
#28
