### ISSUE TITLE
Застопить баннер

### ISSUE THREAD

**Issue by ice-death** [userbq201/banners#32]
Необходимо реализовать остановку баннера на указанном временном промежутке.
Остановка баннера должна быть выполнена путем остановки функции слушателя "tick".
Должна быть возможность указания на каком цикле баннер должен остановиться.

**Comment by userbq201** [comment]
Не понял. Скрины или объяснение подробнее.

**Comment by ice-death** [comment]
Вот тут  добавляется слушатель http://joxi.ru/Rmz1zqgcWxXG5r
Необходимо добавлять в код таймер, который по заданному времени будет этот слушатель удалять.
createjs.Ticker.removeEventListener('tick', stage);

**Comment by ice-death** [comment]
Вот тут  добавляется слушатель ![image](http://joxi.ru/Rmz1zqgcWxXG5r)
Необходимо добавлять в код таймер, который по заданному времени будет этот слушатель удалять.
createjs.Ticker.removeEventListener('tick', stage);

**Comment by ice-death** [comment]
Надо в любом случае добавить возможность выбора цикла. Т.е. Если выбрано "0" - то баннер останавливается на первом цикле, если "1" - то соответственно на втором и т.д.

**Comment by userbq201** [comment]
@ice-death это не проблема. `fps * n`, где `n` кол-во повторений. Пока не в этом трабла

**Comment by userbq201** [comment]
@ice-death на макете не видел как это выглядит
